# Generated by Django 4.0.3 on 2022-04-02 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('view_item', 'View Item'),)},
        ),
    ]
